### ISSUE TITLE
Unexpected Crash on Windows when using Stb

### ISSUE THREAD

**Issue by Edoardo-Morosanu** [treeform/pixie#380] opened 2022-02-11 18:41 UTC
When trying to read a JPG image, the program crashes unexpectedly, on Windows 11.

This is the example code I tried to run:
```Nim
import pixie
let image = readImage("test.jpg")
```

# Additional Information
Nim Compiler Version 1.6.4 [Windows: amd64]
Pixie version: 3.1.4
Compiled with `nim c -d:pixieUseStb test.nim`
When I run the program it suddenly crashes with no debug traceback.
It works fine for reading PNG images.

**Comment by treeform** [comment] 2022-02-11 18:54
Do you have the test.jpg?

**Comment by Edoardo-Morosanu** [comment] 2022-02-11 19:15
Sure, here's the image.
![test](https://user-images.githubusercontent.com/92819547/153655148-ea91434b-a69e-4f0f-bb05-8e3da3e91bbd.jpg)

**Comment by guzba** [comment] 2022-02-11 19:59
I tested loading this jpg on Mac and Windows 10 and everything worked fine (Nim 1.6.4, refc and arc).

Do all jpgs fail or just a specific one? What Nim version are you using (`nim -v`).

I don't have access to Windows 11 and am not at all interested in upgrading so if this is a Windows 11 specific issues, that'll be tough. I doubt it is though.

**Comment by Edoardo-Morosanu** [comment] 2022-02-11 20:03
I tried with more than one JPG file and the program always fails.
```
Nim Compiler Version 1.6.4 [Windows: amd64]
Compiled at 2022-02-09
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by guzba** [comment] 2022-02-11 20:16
Could you try loading the image using this stb_image binding and see if the same thing happens there? https://github.com/define-private-public/stb_image-Nim

**Comment by Edoardo-Morosanu** [comment] 2022-02-11 21:20
I tried it, and stb_image works fine.
```nim
import stb_image/read as stbi

var
  width, height, channels: int
  data: seq[uint8]

data = stbi.load("test.jpg", width, height, channels, stbi.Default)

echo "12345"
```

**Comment by guzba** [comment] 2022-02-11 21:50
Ok, that's good to see. One thing though, we do not use the file loading version, we use stbi_load_from_memory since we need to support files or buffers. Maybe that is the difference?

https://github.com/define-private-public/stb_image-Nim/blob/ba5f45286bfa9bed93d8d6b941949cd6218ec888/stb_image/read.nim#L59

Since I can't reproduce the issue I'm not able to try any of this myself.

It is mostly the same call but you'll `var data = readFile("test.jpg")`. Then pass in `data[0].addr` and data.len.

In the meantime ill try grabbing the latest source, maybe it has some fix?

**Comment by Edoardo-Morosanu** [comment] 2022-02-12 19:46
This code works fine.
```nim
import stb_image/read

var
  width, height, channels: int
  data: seq[byte]
  file = open("test.jpg", fmRead)
  str = file.readAll()

data.setLen(len(str))
copyMem(addr data[0], addr str[0], len(str))

let image = loadFromMemory(data, width, height, channels, Default)
echo "Pixels: ", image.len

```

**Comment by guzba** [comment] 2022-02-12 23:26
Hm, ok well I wish I could reproduce this to work on it.

If you're up for more debugging, could you try putting maybe `echo`s in or something to see how far it gets into `readFile`?

For example, we have a very tiny wrapper for JPG using stb_image: https://github.com/treeform/pixie/blob/master/src/pixie/fileformats/stb_image/stb_image.nim

If you put `echo`s in there at each line, what line does it crash on? Maybe try commenting out some stuff and see if you can learn anything to share?

**Comment by Edoardo-Morosanu** [comment] 2022-02-14 17:01
You know what? I was trying to debug the library once again, when I noticed that it just began to work. I tried to find the culprit, with no success. I tried reinstalling the whole library from nimble, and it doesn't crash anymore. I guess we can mark this issue as solved, thank y'all!

**Comment by MetaphysicianLeo** [comment] 2022-04-26 14:05
Seems I have the same problem too.  But when I try to install stb_image-Nim and rebuild the program, got something different output.

code here
```
import std/json
import pixie
import pixie/fileformats/jpg
import utils/similarity
import stb_image/read as stbi

type Path = string

type Config = object
  target: Path
  genefile: Path


const config_file = "./config.json"
var config: Config = parseFile(config_file).to(Config)

proc save() = 
  var file = open(config_file, FileMode.fmWrite)
  file.write((%config).pretty())
  file.close()


echo "aa"
when isMainModule:
  # var target = readImage(config.target)
  # # echo pHash(target, readImage("target/aff0d2cd8ac171e8.png"))
  # # echo histogram(target, readImage("target/aff0d2cd8ac171e8.png"), HistogramType.htGrey)
  # echo pHash(decodeJpg("target/sample_1.jpg"), decodeJpg("target/sample_2.jpg"))
  echo histogram(readImage("target/sample_1.jpg"), readImage("target/sample_2.jpg"), HistogramType.htGrey)
  # # echo("Hello, World!")

  # var
    # width, height, channels: int
    # data: seq[uint8]
  # data = stbi.load("target/sample_1.jpg", width, height, channels, stbi.Default)
```


```
Hint:  [Link]
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x1fb): multiple definition of \`stbi_failure_reason'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0x17f): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x4ec): multiple definition of \`stbi_image_free'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0x3aa): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x508): multiple definition of \`stbi_set_flip_vertically_on_load'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0x3c6): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x108f): multiple definition of \`stbi_load_16_from_memory'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xa64): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x110a): multiple definition of \`stbi_load_16_from_callbacks'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xadf): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x1187): multiple definition of \`stbi_load_from_memory'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xb5c): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x1202): multiple definition of \`stbi_load_from_callbacks'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xbd7): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x164c): multiple definition of \`stbi_is_hdr_from_memory'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xc54): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x175a): multiple definition of \`stbi_is_hdr_from_callbacks'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xc66): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x17dc): multiple definition of \`stbi_hdr_to_ldr_gamma'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xc79): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x17fd): multiple definition of \`stbi_hdr_to_ldr_scale'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xc9a): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x18dc0): multiple definition of \`stbi_info_from_memory'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xcc20): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x18e37): multiple definition of \`stbi_info_from_callbacks'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xcc97): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x18eb0): multiple definition of \`stbi_is_16_bit_from_memory'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xcd10): first defined here
c:/users/{USERNAME}/dev-env/nim-1.6.0/dist/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o:read.c:(.text+0x18efe): multiple definition of \`stbi_is_16_bit_from_callbacks'; C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o:stb_image.c:(.text+0xcd5e): first defined here
collect2.exe: error: ld returned 1 exit status
Error: execution of an external program failed: 'C:\Users\{USERNAME}\dev-env\nim-1.6.0\dist\mingw64\bin\gcc.exe   -o C:\Users\{USERNAME}\source\hawk\hawk.exe  C:\Users\{USERNAME}\nimcache\hawk_d\stb_image.c.o C:\Users\{USERNAME}\nimcache\hawk_d\read.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_digitsutils.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_assertions.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_formatfloat.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_dollars.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_widestrs.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_io.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_system.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_hashes.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_math.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_parseutils.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_unicode.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_strutils.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_streams.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_lexbase.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_parsejson.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_json.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@svmath-1.1.4@svmath.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@sbumpy-1.1.0@sbumpy.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@schroma-0.2.5@schroma@snames.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@schroma-0.2.5@schroma@scolortypes.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@schroma-0.2.5@schroma@stransformations.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@schroma-0.2.5@schroma.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_dynlib.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_winlean.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_times.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_win_setenv.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_os.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@scommon.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sblends.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sinternal.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@smasks.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@simages.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@spaints.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@spaths.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_parsexml.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_strtabs.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_xmltree.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\stdlib_xmlparser.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@scontexts.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@sbmp.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy@scommon.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy@sinternal.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy@sbitstreams.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@sgif.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@sstb_image@sstb_image.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@sjpg.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy@scrc.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy@sinflate.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy@sgzip.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@szippy-0.9.7@szippy.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@spng.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@sppm.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@sqoi.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie@sfileformats@ssvg.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@m..@s..@s..@s.nimble@spkgs@spixie-4.1.0@spixie.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@mutils@ssimilarity.nim.c.o C:\Users\{USERNAME}\nimcache\hawk_d\@mhawk.nim.c.o    '
     Error: Build failed for package: hawk
        ... Execution failed with exit code 1
        ... Command: C:\Users\{USERNAME}\dev-env\nim-1.6.0\bin\nim.exe c --colors:on --noNimblePath -d:pixieUseStb -d:NimblePkgVersion=0.1.0 --pathth:C:\Users\{USERNAME}\.nimble\pkgs\bumpy-1.1.0 --path:C:\Users\{USERNAME}\.nimble\pkgs\vmath-1.1.4 --path:C:\Users\{USERNAME}\.nimble\pkgs\stb_image-2.5 -o:C:\Users\{USERNAME}\source\hawk\hawk.exe C:\Users\{USERNAME}\source\hawk\src\hawk.nim
```

when I remove 
`import stb_image/read as stbi`
and run 
`nimble -d:pixieUseStb run`
crashes with no output

**Comment by MetaphysicianLeo** [comment] 2022-04-26 14:10
Same problem 
```
import std/json
import pixie
import pixie/fileformats/jpg
import utils/similarity

type Path = string

type Config = object
  target: Path
  genefile: Path


const config_file = "./config.json"
var config: Config = parseFile(config_file).to(Config)

proc save() = 
  var file = open(config_file, FileMode.fmWrite)
  file.write((%config).pretty())
  file.close()


echo "aa"
when isMainModule:
  # var target = readImage(config.target)
  # # echo pHash(target, readImage("target/aff0d2cd8ac171e8.png"))
  # # echo histogram(target, readImage("target/aff0d2cd8ac171e8.png"), HistogramType.htGrey)
  # echo pHash(decodeJpg("target/sample_1.jpg"), decodeJpg("target/sample_2.jpg"))
  echo histogram(readImage("target/sample_1.jpg"), readImage("target/sample_2.jpg"), HistogramType.htGrey)
```

`nimble run`

```
aa
C:\Users\11864\source\hawk\src\hawk.nim(28) hawk
C:\Users\11864\.nimble\pkgs\pixie-4.1.0\pixie.nim(51) readImage
C:\Users\11864\.nimble\pkgs\pixie-4.1.0\pixie.nim(26) decodeImage
C:\Users\11864\.nimble\pkgs\pixie-4.1.0\pixie\fileformats\jpg.nim(12) decodeJpg
Error: unhandled exception: Decoding JPG requires -d:pixieUseStb [PixieError]
```

`nimble -d:pixieUseStb run`
crashes and no output

**Comment by MetaphysicianLeo** [comment] 2022-04-26 14:36
Same problem
```
import std/json
import pixie
import pixie/fileformats/jpg
import utils/similarity

type Path = string

type Config = object
  target: Path
  genefile: Path


const config_file = "./config.json"
var config: Config = parseFile(config_file).to(Config)

proc save() = 
  var file = open(config_file, FileMode.fmWrite)
  file.write((%config).pretty())
  file.close()


echo "aa"
when isMainModule:
  # var target = readImage(config.target)
  # # echo pHash(target, readImage("target/aff0d2cd8ac171e8.png"))
  # # echo histogram(target, readImage("target/aff0d2cd8ac171e8.png"), HistogramType.htGrey)
  # echo pHash(decodeJpg("target/sample_1.jpg"), decodeJpg("target/sample_2.jpg"))
  echo histogram(readImage("target/sample_1.jpg"), readImage("target/sample_2.jpg"), HistogramType.htGrey)
```


`nimble run`
```
aa
C:\Users\{USERNAME}\source\hawk\src\hawk.nim(28) hawk
C:\Users\{USERNAME}\.nimble\pkgs\pixie-4.1.0\pixie.nim(51) readImage
C:\Users\{USERNAME}\.nimble\pkgs\pixie-4.1.0\pixie.nim(26) decodeImage
C:\Users\{USERNAME}\.nimble\pkgs\pixie-4.1.0\pixie\fileformats\jpg.nim(12) decodeJpg
Error: unhandled exception: Decoding JPG requires -d:pixieUseStb [PixieError]
```
when I run
`nimble -d:pixieUseStb run`
the program crashes and no output

**Comment by MetaphysicianLeo** [comment] 2022-05-11 17:41
> Hey, we been working on a pure Nim jpeg decoder. By trying `head` can you see it if works for you?
> 
> To get most recent pixie do a git clone: `git clone https://github.com/treeform/pixie` Then install it: `cd pixie` `nimble develop`
> 
> Then try jpeg decoder without `-d:pixieUseStb` flag.
> 
> I tested your "GIMP" image with our new decoder and it works great here.
> 
> Thanks!

It works.

**Comment by guzba** [comment] 2022-05-23 23:54
We have tagged 4.3.0 which includes the new pre Nim decoder. Closing this issue since we no longer use stb_image.

Thanks for confirming it is working @MetaphysicianLeo

**Closed by guzba** 2022-05-23 23:54 UTC
